config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home', as: 'pages_home'

  devise_for :users
  
  get '/contact', to: 'pages#contact', as: 'pages_contact'

  post '/contact', to: 'pages#contact_email'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!, except: [:home]

  def home
  end

  def contact
  end

  def contact_email
    user_info = {
      user: current_user, 
      name: email_params[:name],
      message: email_params[:message],
    }
    ContactMailer.send_contact_email(user_info).deliver_now
    render :home
  end
end


private

def email_params
  params.require(:contact).permit(:name, :message)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstarailsMailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render  "pages/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Rails Mailgun Tutorial</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Home", pages_home_path, :class => "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Send Message", pages_contact_path, :class => "nav-link"%>
      </li>
    </ul>
  </div>
</nav>

app/views/pages/contact.html.erb
<h3>Send Me a Message</h3>
<br>
<div class="form">
    <%= form_for :contact do |f| %>
        <p>
        <%= f.label :name %>
        <br>
        <%= f.text_field :name, class: "form-control"%>
        </p>
        <p>
        <%= f.label :message %>
        <br>
        <%= f.text_area :message, rows: '8', class: "form-control" %>
        </p>
        <p>
        <%= f.submit 'Submit', class: "btn btn-primary"%>
        </p>
    <% end %>
</div>

<hr>

app/views/pages/home.html.erb
<h3>Instarails Project</h3>
<large class="text-muted">Coder Academy - Term 2</large>
<br>
<br>
<p>This is my rails mailgun gem test app as demonstrated in term two of the CoderAcademy bootcamp.</p>
<div class="instructions">
    <p class="font-weight-bold">Instructions</p>
    <ul>
        <li>Click the Contact button.</li>
        <li>Or the Send Messge link at the top right of the navbar.</li>
        <li>Fill out the contact form.</li>
        <li>Click Submit to send your message.</li>
        <li>I will recieve an email with your message.</li>
    </ul>
    <br>
    <%= link_to  "Contact", contact_path, class: "btn btn-success" %>
</div>